// tests/full-flow.spec.ts
// E2E Test for Campus Hub App
// Full flow: Login -> Create Event -> RSVP

import { test, expect } from '@playwright/test';

// Test credentials from environment variables
// Set TEST_EMAIL and TEST_PASSWORD in your .env.local file
const TEST_EMAIL = process.env.TEST_EMAIL || '';
const TEST_PASSWORD = process.env.TEST_PASSWORD || '';

test.describe('Campus Hub Full Flow', () => {
  test.beforeEach(async ({ page }) => {
    // Clear any existing session
    await page.context().clearCookies();
  });

  test('Full flow: Login -> Create Event -> RSVP', async ({ page }) => {
    // ============================================
    // STEP 1: Login (Using Guest Login - no Google Auth needed!)
    // ============================================
    console.log('Step 1: Navigating to login page...');
    await page.goto('/login');
    
    // Wait for the login page to load
    await expect(page.getByRole('button', { name: /Sign in as Guest/i })).toBeVisible();
    
    // Click "Sign in as Guest" button (this uses email/password internally)
    // This avoids Google OAuth popup which Playwright can't handle easily
    await page.getByRole('button', { name: /Sign in as Guest/i }).click();
    
    // Wait for success toast to appear (indicates login worked)
    // Look for the toast description text since "Welcome Back" is also a page heading
    await expect(page.getByText(/Logged in as guest successfully/i).first()).toBeVisible({ timeout: 30000 });
    
    // Now wait for redirect to home page
    await expect(page).toHaveURL('/', { timeout: 15000 });
    console.log('✓ Guest login successful');

    // ============================================
    // STEP 2: Navigate and Click "Post Event"
    // ============================================
    console.log('Step 2: Opening Create Event dialog...');
    
    // Click "Post Event" button (may say "Post Event" or be a button with that text)
    await page.getByRole('button', { name: /Post Event/i }).click();
    
    // Wait for the dialog to open
    await expect(page.getByRole('dialog')).toBeVisible();
    console.log('✓ Create Event dialog opened');

    // ============================================
    // STEP 3: Fill out the Create Event form
    // ============================================
    console.log('Step 3: Filling out event form...');
    
    // Click "Fill Form Manually" to skip AI generation
    await page.getByRole('button', { name: /Fill Form Manually/i }).click();
    
    // Wait for the form to appear
    await expect(page.locator('#title')).toBeVisible();
    
    // Select "College Event" type (should be default, but click to be sure)
    await page.getByLabel('College Event').click();
    
    // Fill Event Title
    await page.fill('#title', 'Automated Test Event');
    
    // Fill Description
    await page.fill('#description', 'This is a test event generated by Playwright E2E testing. Please ignore this event.');
    
    // Select Category (click the select and choose an option) - scope to dialog
    const dialog = page.getByRole('dialog');
    await dialog.locator('button[role="combobox"]').first().click();
    await page.getByRole('option', { name: 'Tech' }).click();
    
    // Fill Venue
    await page.fill('#venue', 'Test Venue - Room 101');
    
    // Fill Date (set to a future date with time)
    const futureDate = new Date();
    futureDate.setDate(futureDate.getDate() + 7); // 7 days from now
    futureDate.setHours(14, 0, 0, 0); // Set to 2:00 PM
    // Format for datetime-local: YYYY-MM-DDTHH:MM
    const dateString = futureDate.toISOString().slice(0, 16);
    await page.fill('#date', dateString);
    
    // Select Location (City) - click the city select dropdown (scope to dialog)
    await dialog.locator('button[role="combobox"]').nth(1).click();
    await page.getByRole('option', { name: 'Ahmedabad' }).click();
    
    console.log('✓ Event form filled');

    // ============================================
    // STEP 4: Submit the form and wait for success
    // ============================================
    console.log('Step 4: Submitting event...');
    
    // Click the "Post Event" button inside the dialog
    await page.getByRole('button', { name: /Post Event/i }).last().click();
    
    // Wait for success toast
    await expect(page.getByText(/Event Created/i).first()).toBeVisible({ timeout: 10000 });
    console.log('✓ Event created successfully');
    
    // Dialog should close
    await expect(page.getByRole('dialog')).not.toBeVisible({ timeout: 5000 });

    // ============================================
    // STEP 5: Navigate to the newly created event
    // ============================================
    console.log('Step 5: Finding and opening the created event...');
    
    // Find the event card with our title and click the "Discuss" link to view details
    const eventCard = page.locator('article, [class*="card"]').filter({ hasText: 'Automated Test Event' }).first();
    await expect(eventCard).toBeVisible({ timeout: 10000 });
    
    // Click the Discuss button/link to navigate to the event page
    await eventCard.getByRole('link', { name: /Discuss/i }).click();
    
    // Wait for navigation to event details page
    await expect(page).toHaveURL(/\/events\//, { timeout: 10000 });
    console.log('✓ Navigated to event details page');

    // ============================================
    // STEP 6: Click RSVP & Get Ticket button
    // ============================================
    console.log('Step 6: Clicking RSVP button...');
    
    // Find and click the RSVP button
    const rsvpButton = page.getByRole('button', { name: /RSVP & Get Ticket/i });
    await expect(rsvpButton).toBeVisible();
    await rsvpButton.click();
    
    // Wait for the QR code dialog or confirmation
    await expect(page.getByRole('dialog')).toBeVisible({ timeout: 10000 });
    console.log('✓ RSVP successful - QR ticket displayed');

    // ============================================
    // STEP 7: Verify button changed to "View Ticket"
    // ============================================
    console.log('Step 7: Verifying ticket state...');
    
    // Close the QR dialog first
    await page.keyboard.press('Escape');
    
    // The button should now say "View Ticket" instead of "RSVP & Get Ticket"
    await expect(page.getByRole('button', { name: /View Ticket/i })).toBeVisible({ timeout: 5000 });
    console.log('✓ Button changed to "View Ticket"');

    console.log('\n========================================');
    console.log('🎉 All tests passed successfully!');
    console.log('========================================');
  });

  // Additional test: Login with email/password (needs manual user in Supabase)
  test.skip('should login with email/password credentials', async ({ page }) => {
    await page.goto('/login');
    
    await page.fill('input[type="email"]', TEST_EMAIL);
    await page.fill('input[type="password"]', TEST_PASSWORD);
    await page.click('button[type="submit"]');
    
    await expect(page).toHaveURL('/', { timeout: 10000 });
  });

  // Additional test: Guest login
  // NOTE: This test requires Supabase CORS to be configured to allow localhost:9002
  test('should login as guest', async ({ page }) => {
    await page.goto('/login');
    
    // Click "Sign in as Guest" button
    await page.getByRole('button', { name: /Sign in as Guest/i }).click();
    
    // Wait for the URL to change to home page (this indicates successful login)
    // Timeout extended because Supabase auth + profile loading can take time
    await expect(page).toHaveURL('/', { timeout: 30000 });
    
    // Verify we're on the home page by checking for the Post Event button
    await expect(page.getByRole('button', { name: /Post Event/i })).toBeVisible({ timeout: 10000 });
  });

  // Additional test: Navigation check
  test('should navigate to different pages', async ({ page }) => {
    // Login first using Guest
    await page.goto('/login');
    await page.getByRole('button', { name: /Sign in as Guest/i }).click();
    
    // Wait for redirect to home page
    await expect(page).toHaveURL('/', { timeout: 30000 });
    
    // Wait for page to fully load
    await expect(page.getByRole('button', { name: /Post Event/i })).toBeVisible();

    // Open the avatar dropdown menu
    await page.locator('header').getByRole('button').first().click();
    await expect(page.getByRole('menu')).toBeVisible();
    
    // Navigate to Leaderboard
    await page.getByRole('menuitem', { name: /Leaderboard/i }).click();
    await expect(page).toHaveURL('/leaderboard', { timeout: 10000 });
    
    // Verify leaderboard page content
    await expect(page.getByRole('heading', { name: /Leaderboard/i })).toBeVisible({ timeout: 5000 });

    // Open dropdown again - leaderboard page has header
    await page.locator('header').getByRole('button').first().click();
    await expect(page.getByRole('menu')).toBeVisible();
    
    // Navigate to Profile
    await page.getByRole('menuitem', { name: /Profile/i }).click();
    await expect(page).toHaveURL('/profile', { timeout: 10000 });
  });
});
